import os
DATABASE_URL = os.getenv('SQLALCHEMY_DATABASE_URI', 'sqlite:///database.db')
SQLALCHEMY_TRACK_MODIFICATIONS=os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS', False)
STAND=os.getenv('STAND', 'TEST')
if STAND == 'TEST':
    TELEGRAM_TOKEN=os.getenv('TELEGRAM_TOKEN_TEST', 'TOKEN')
else:
    TELEGRAM_TOKEN=os.getenv('TELEGRAM_TOKEN_PROD', 'TOKEN')
FLIGHT_API_KEY=os.getenv('FLIGHT_API_KEY', '')
OPENAI_API_KEY=os.getenv('OPENAI_API_KEY', '')
DEBUG_MODE=os.getenv('DEBUG_MODE', False)
MAX_TELEGRAM_MESSAGE_LEN=os.getenv('MAX_TELEGRAM_MESSAGE_LEN', 100)
